# Generated by Django 4.0.3 on 2022-07-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_link_alter_fromcomp_post_postlinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='PostLinks',
        ),
    ]
