# Generated by Django 4.0.3 on 2022-07-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_delete_link_delete_postlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.fromcomp')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('index', models.IntegerField()),
                ('post_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.postlinks')),
            ],
        ),
    ]
