# Generated by Django 4.0.3 on 2022-07-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_postlinks_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLinks',
            new_name='PostLink',
        ),
    ]
