# Generated by Django 4.0.3 on 2022-07-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_postlinks_postlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlink',
            name='post',
        ),
        migrations.AlterField(
            model_name='fromcomp',
            name='post',
            field=models.TextField(default='', max_length=1200),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='PostLink',
        ),
    ]
