# Generated by Django 4.0.3 on 2022-07-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_remove_postlink_post_alter_fromcomp_post_delete_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsb',
            name='user',
        ),
    ]
