# Generated by Django 4.0.3 on 2022-07-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_orders_state_delete_orderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsb',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='App1.user'),
        ),
    ]
