# Generated by Django 4.0.3 on 2022-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_postlink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='index',
            field=models.CharField(default='Post', max_length=455),
        ),
    ]
